site_name: Vjudge

repo_url: https://github.com/Interacao-Humano-Computador/2020.2-Vjudge
repo_name: 'Vjudge'

theme:
  name: material
  language: 'pt'
  logo: 'assets/icons/vjudge.png'
  favicon: 'assets/icons/codercat.png'

extra_css:
  - stylesheets/extra.css

nav:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Processo de design:
      - Usabilidade de Mayhew: processoDeDesign/usabilidadeDeMayhew.md
  - Análise de requisitos:  
    - Análise de Tarefas:
      - G.O.M.S.: analiseDeRequisitos/analiseDeTarefas/goms.md
      - Árvores de tarefas concorrentes: analiseDeRequisitos/analiseDeTarefas/ctt.md
    - Perfil do usuário:
      - Personas: analiseDeRequisitos/perfilDoUsuario/personas.md
  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao1.md
      - Apresentação 2: apresentacoes/apresentacao2.md
  - Atas de reunião:
      - Reunião 1: atas/atas1.md
      - Reunião 2: atas/atas2.md