site_name: Vjudge

repo_url: https://github.com/Interacao-Humano-Computador/2020.2-Vjudge
repo_name: 'Vjudge'

theme:
  name: material
  language: 'pt'
  logo: 'assets/icons/vjudge.png'
  favicon: 'assets/icons/codercat.png'
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

nav:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Processo de design:
      - Usabilidade de Mayhew: processoDeDesign/usabilidadeDeMayhew.md
  - Análise de requisitos:  
    - Análise de Tarefas:
      - G.O.M.S.: analiseDeRequisitos/analiseDeTarefas/goms.md
      - Árvores de tarefas concorrentes: analiseDeRequisitos/analiseDeTarefas/ctt.md
    - Perfil do usuário:
      - Personas: analiseDeRequisitos/perfilDoUsuario/personas.md
    - Princípios Gerais de Projeto: analiseDeRequisitos/principiosGeraisDeProjeto.md
    - Metas de usabilidade: analiseDeRequisitos/metasDeUsabilidade.md
    - Guia de Estilo: analiseDeRequisitos/guiaDeEstilo.md
  - Design, Avaliação e Desenvolvimento:
    - Nível 1:
      - Análise de Tarefas:
        - Planejamento da Avaliação da Análise de tarefas: designAvaliacaoDesenvolvimento/nivel1/analiseDeTarefas/planejamentoAvaliacaoDaAnaliseDeTarefas.md
        - Relato de resultados da Avaliação da Análise de tarefas: designAvaliacaoDesenvolvimento/nivel1/analiseDeTarefas/relatoDeResultadosDaAnaliseDeTarefas.md
        - Entrevistas:
          - João (Aluno): designAvaliacaoDesenvolvimento/nivel1/analiseDeTarefas/entrevistas/entrevistaJoao.md
          - Álvaro (Aluno): designAvaliacaoDesenvolvimento/nivel1/analiseDeTarefas/entrevistas/entrevistaAlvaro.md
          - Bruno Ribas (Professor): designAvaliacaoDesenvolvimento/nivel1/analiseDeTarefas/entrevistas/entrevistaBruno.md
          - John Lenon (Professor): designAvaliacaoDesenvolvimento/nivel1/analiseDeTarefas/entrevistas/entrevistaJohn.md
      - Storyboards:
        - Storyboards: designAvaliacaoDesenvolvimento/nivel1/storyboards/storyboards.md
        - Planejamento da Avaliação dos Storyboards: designAvaliacaoDesenvolvimento/nivel1/storyboards/planejamentoAvaliacaoDoStoryboard.md
        - Relato de resultados da Avaliação dos Storyboards: designAvaliacaoDesenvolvimento/nivel1/storyboards/relatoDeResultadosDoStoryboards.md
        - Entrevistas:
          - João (Aluno): designAvaliacaoDesenvolvimento/nivel1/storyboards/entrevistas/entrevistaJoao.md
          - Álvaro (Aluno): designAvaliacaoDesenvolvimento/nivel1/storyboards/entrevistas/entrevistaAlvaro.md
          - Bruno Ribas (Professor): designAvaliacaoDesenvolvimento/nivel1/storyboards/entrevistas/entrevistaBruno.md
          - John Lenon (Professor): designAvaliacaoDesenvolvimento/nivel1/storyboards/entrevistas/entrevistaJohn.md
    - Nível 2:
      - Protótipo de Papel:
        - Planejamento da Avaliação do Protótipo de Papel: designAvaliacaoDesenvolvimento/nivel2/prototipoDePapel/planejamentoAvaliacaoDoPrototipoDePapel.md
        - Relato dos resultados da Avaliação do Protótipo de Papel: designAvaliacaoDesenvolvimento/nivel2/prototipoDePapel/relatoDeResultadosDoPrototipoDePapel.md
        - Entrevistas:
          - Teste-Piloto: designAvaliacaoDesenvolvimento/nivel2/prototipoDePapel/entrevistas/testePiloto.md
          - João (Aluno): designAvaliacaoDesenvolvimento/nivel2/prototipoDePapel/entrevistas/entrevistaJoao.md
          - Álvaro (Aluno): designAvaliacaoDesenvolvimento/nivel2/prototipoDePapel/entrevistas/entrevistaAlvaro.md
    #   - Protótipo de Baixa Fidelidade: designAvaliacaoDesenvolvimento/nivel2/prototipoBaixaFidelidade.md
    - Nível 3:
      - Prot. de Alta Fidelidade:
        - Planejamento da Avaliação do Protótipo de Alta fidelidade: designAvaliacaoDesenvolvimento/nivel3/planejamentoAvaliacaoDoPrototipoDeAltaFidelidade.md
        - Relato dos resultados da Avaliação do Protótipo de Papel: designAvaliacaoDesenvolvimento/nivel3/relatoDeResultadosDoPrototipoDeAltaFidelidade.md
        - Entrevistas:
          - Álvaro (Aluno): designAvaliacaoDesenvolvimento/nivel3/entrevistas/entrevistaAlvaro.md
          - John Lenon (Professor): designAvaliacaoDesenvolvimento/nivel3/entrevistas/entrevistaJohn.md
  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao1.md
      - Apresentação 2: apresentacoes/apresentacao2.md
      - Apresentação 3: apresentacoes/apresentacao3.md
      - Apresentação 4: apresentacoes/apresentacao4.md
      - Apresentação 5: apresentacoes/apresentacao5.md
      - Apresentação 6: apresentacoes/apresentacao6.md
  - Atas de reunião:
      - Reunião 1: atas/atas1.md
      - Reunião 2: atas/atas2.md
      - Reunião 3: atas/atas3.md
      - Reunião 4: atas/atas4.md
      - Reunião 5: atas/atas5.md
      - Reunião 6: atas/atas6.md