site_name: Vjudge

repo_url: https://github.com/Interacao-Humano-Computador/2020.2-Vjudge
repo_name: 'Vjudge'

theme:
  name: material
  language: 'pt'
  logo: 'assets/icons/vjudge.png'
  favicon: 'assets/icons/codercat.png'
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

nav:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Processo de design:
      - Usabilidade de Mayhew: processoDeDesign/usabilidadeDeMayhew.md
  - Análise de requisitos:  
    - Análise de Tarefas:
      - G.O.M.S.: analiseDeRequisitos/analiseDeTarefas/goms.md
      - Árvores de tarefas concorrentes: analiseDeRequisitos/analiseDeTarefas/ctt.md
    - Perfil do usuário:
      - Personas: analiseDeRequisitos/perfilDoUsuario/personas.md
    - Princípios Gerais de Projeto: analiseDeRequisitos/principiosGeraisDeProjeto.md
    - Metas de usabilidade: analiseDeRequisitos/metasDeUsabilidade.md
    - Guia de Estilo: analiseDeRequisitos/guiaDeEstilo.md
  - Design, Avaliação e Desenvolvimento:
    - Nível 1:
      - Planejamento da Avaliação da Análise de tarefas: designAvaliacaoDesenvolvimento/nivel1/planejamentoAvaliacaoDaAnaliseDeTarefas.md
      - Storyboards: designAvaliacaoDesenvolvimento/nivel1/storyboards.md
      - Planejamento da Avaliação dos Storyboards: designAvaliacaoDesenvolvimento/nivel1/planejamentoAvaliacaoDoStoryboard.md
    # - Nível 2:
    #   - Protótipo de Baixa Fidelidade: designAvaliacaoDesenvolvimento/nivel2/prototipoBaixaFidelidade.md
    #   - Planejamento da Avaliação do Protótipo de Baixa fidelidade: designAvaliacaoDesenvolvimento/nivel2/planejamentoAvaliacaoDoPrototipoDeBaixaFidelidade.md
    # - Nível 3:
    #   - Protótipo de Alta Fidelidade: designAvaliacaoDesenvolvimento/nivel3/prototipoAltaFidelidade.md
    #   - Planejamento da Avaliação do Protótipo de Alta fidelidade: designAvaliacaoDesenvolvimento/nivel3/planejamentoAvaliacaoDoPrototipoDeAltaFidelidade.md
  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao1.md
      - Apresentação 2: apresentacoes/apresentacao2.md
      - Apresentação 3: apresentacoes/apresentacao3.md
      - Apresentação 4: apresentacoes/apresentacao4.md
  - Atas de reunião:
      - Reunião 1: atas/atas1.md
      - Reunião 2: atas/atas2.md
      - Reunião 3: atas/atas3.md
      - Reunião 4: atas/atas4.md